#!/bin/bash

#
# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

sudo yabai --load-sa

yabai_conf=(
  external_bar all:52:0
  mouse_follows_focus off
  focus_follows_mouse off
  window_origin_display default
  window_placement second_child
  window_zoom_persist on
  window_shadow on
  window_animation_duration 0.0
  window_opacity_duration 0.0
  active_window_opacity 1.0
  normal_window_opacity 0.90
  window_opacity off
  insert_feedback_color 0xffd75f5f
  split_ratio 0.50
  split_type auto
  auto_balance on
  top_padding 12
  bottom_padding 12
  left_padding 8
  right_padding 8
  window_gap 12
  layout bsp
  mouse_modifier alt
  mouse_action1 move
  mouse_action2 resize
  mouse_drop_action stack
)

yabai -m config "${yabai_conf[@]}"
echo "yabai configuration loaded.."
